sudo: required

language: c

os:
 - linux

compiler:
 - gcc

before_script:
 - sudo apt-get install libldns
 - git clone https://github.com/jedisct1/libsodium.git --branch=stable
 - cd libsodium
 - ./autogen.sh
 - ./configure --disable-dependency-tracking
 - sudo make install
 - sudo ldconfig
 - cd ..
 - ./autogen.sh
 - ./configure --disable-dependency-tracking --enable-plugins

script:
 - make -j$(nproc)

matrix:
 - fast_finish: true
